### ISSUE TITLE
[Contribution] Deep Learning Workflows

### ISSUE THREAD

**Issue by surajpaib** [MaastrichtU-IDS/dsri-documentation#11]
Hi Team,

I've been using the OC Pods for a variety of DL related tasks - preprocessing, training and deployment, and have documented some workflows for the rest of our team at Maastro. 

One of the first ones is setting up Visual Studio Code server so that we can use a robust and powerful file editor to work with our projects. 

I'm issuing a PR to the repo with my additions and documentation. If you think this might be useful to a larger audience beyond the Maastro group, I propose adding this to the existing documentation.

Thanks!

**Comment by vemonet** [comment]
Hi Suraj, thanks a lot for this contribution!

We accepted the pull request, and we will take a look in making it easier

They have a Docker image that can be used: https://github.com/cdr/code-server/blob/v3.4.1/doc/install.md#docker

We can define a template to create VSCode pods from the web UI

**Comment by surajpaib** [comment]
The docker image sounds perfect. Let me know if I can help test the template out. Would be a much more elegant solution

**Comment by vemonet** [comment]
![Screenshot from 2020-09-01 15-14-57](https://user-images.githubusercontent.com/3778439/91855963-31876e80-ec66-11ea-920e-4e2b3695d7a2.png)

You can do it now! It worked on my side, you deploy it on your persistent storage at the path you want 
I am surprised at how fast it is working! I was expecting it to be a bit slow, but it is actually faster than my personal VSCode

Here is all you need to provide to create it:

![Screenshot from 2020-09-01 15-18-08](https://user-images.githubusercontent.com/3778439/91858509-92647600-ec69-11ea-9ebe-dfdce197e1f2.png)

You should be able to access the template in `maastroc-domain-adaptation`

**Comment by vemonet** [comment]
The next step would be to add GPU support to the VisualStudio Code image I guess

Here we have 2 options:
* Use the Nvidia image provided for GPU and install VisualStudio Code (I guess this is what you did @surajpaib ?)
* Install dependencies to enable GPU in the VisualStudio Code server image

**Comment by surajpaib** [comment]
Hi Vincent! Great to see this added so quick! I did follow the first option as you pointed out. 

Both options seem good to me. Would there be any significant differences between the two for the end-user?

**Comment by vemonet** [comment]
Going with the Nvidia container would be better, otherwise we would need to find out and install all dependencies for GPU support

I started a template to deploy it from the Web UI, it works with port-forward

But does not work with Routes (to access it directly on the DSRI URLs)

This issue with routing port 8080 is :
*  only appears when installing code-server on other image (even if the port 8080 is exposed in the Dockerfile of this image)
* the port 8080 is properly served inside the pod and to the service (we can do port-forwarding)
* The official Docker image of code-server is able to route to DSRI URLs without issue

**Comment by surajpaib** [comment]
Sorry for the delayed response @vemonet. Was quite busy with some other projects. 

Tested the pytorch VS code images and they look pretty good! I generally use port forwarding so shouldn't be a problem. 

I presume there isn't an easy fix to route to DSRI URLs. Is there something I can perhaps play around with in the code-server config ?

**Comment by surajpaib** [comment]
@vemonet I played around with a few things, using the ```bind-addr``` flag or the field in the config and broadcasting over 0.0.0.0 seems to make the routes work in the GPU image. 

I added a custom port and created a route to test it out: http://gpu-pytorch-vscode-general-test-maastro-domain-adaptation.app.dsri.unimaas.nl/login?to=%2F

**Comment by vemonet** [comment]
Hi @surajpaib 

I added the `bind-addr` directly in the Dockerfile to start it properly (even with Docker you need this to avoid providing `-net host`)

```Dockerfile
ENTRYPOINT [ "code-server" ]
CMD [ "--bind-addr", "0.0.0.0" ]
```

But it does no fix the issue, and I cannot access yours neither: http://gpu-pytorch-vscode-general-test-maastro-domain-adaptation.app.dsri.unimaas.nl/login?to=%2F

**Comment by vemonet** [comment]
Solved starting on 8081
