### ISSUE TITLE
Make a plain Ubuntu container available via the catalog

### ISSUE THREAD

**Issue by wviechtb** [MaastrichtU-IDS/dsri-documentation#20]
For those who are comfortable using DSRI directly via the command line, it would be great if you could make a plain Ubuntu container (with root access) available via the catalog (like https://hub.docker.com/_/ubuntu). That gives full control to experienced users with running whatever combination of command line tools they need for their work.

**Comment by vemonet** [comment]
I just started a template for https://hub.docker.com/_/ubuntu (latest tag)

You can find the template here:
https://github.com/MaastrichtU-IDS/dsri-openshift-applications/blob/main/templates-anyuid/template-ubuntu-root-persistent.yml

I started the documentation here: https://maastrichtu-ids.github.io/dsri-documentation/docs/deploy-additional-services

I will need to test it more later this week to make it work properly

**Comment by vemonet** [comment]
Done, it is using the latest official Ubuntu image from DockerHub. It is not impossible that when importing the image to the DSRI you hit the DockerHub limitations, let me know if this is an issue, we can host the Ubuntu image on a less restricted platform

https://maastrichtu-ids.github.io/dsri-documentation/docs/deploy-additional-services#ubuntu

**Comment by wviechtb** [comment]
Sweet! Just tried it out and works like a charm. Thanks a bunch!
