### ISSUE TITLE
Request deployment of Neuro and imaging applications

### ISSUE THREAD

**Issue by vemonet** [MaastrichtU-IDS/dsri-documentation#21]
#### Describe the application

Deploy images from the NeuroDocker Project: https://miykael.github.io/nipype_tutorial/notebooks/introduction_neurodocker.html

neurodebian

* FSL + Freesurfer (+ FSLeyes)
* Freesurfer + afni
* nighres (python based), and nipype also?
* **Matlab with UI**

Matlab packages: `neuroelf`, `spm12`, with the matlab UI

#### Application Git repository URL

https://miykael.github.io/nipype_tutorial/notebooks/introduction_neurodocker.html

FSLeyes UI:

https://hub.docker.com/r/kaczmarj/fsleyes

#### Notable licensing issues 

Matlab

@fdemarti

**Comment by fdemarti** [comment]
other useful packages:
MRtrix3 (for diffusion imaging)
dcm2niix (this should go in any FSL docker if possible)

also note that the matlab packages SPM12 and neuroelf are useful ALSO if the UI is not available.

**Comment by vemonet** [comment]
@fdemarti we are in discussion with UM to access Matlab licenses but the number of licenses for Matlab at UM are limited

But you should not be using Matlab if you are doing Research or Education funded by public organizations

The goal of research is to produce valuable and reproducible analysis.

When you publish an analysis using a closed software like Matlab you are publishing something that cannot be reused by other scientists, because they would need to pay for Matlab license, and Matlab support (if matlab still exist the year when you want to use it)

Unfortunately, what researchers working with Matlab are doing is to promote a Matlab monopoly in science for the years to come (since scientists will be dependant on matlab later, even if there are better solutions)


I would recommend to any scientist doing public funded science to not use matlab, and use Open Source solutions like R, Python, Julia

**Comment by vemonet** [comment]
We have published some documentation to build and deploy NeuroDocker images:
https://maastrichtu-ids.github.io/dsri-documentation/docs/neuroscience

You can also now easily deploy matlab from a template, see more informations here: https://maastrichtu-ids.github.io/dsri-documentation/docs/deploy-matlab

**Comment by vemonet** [comment]
You can find documentation to deploy popular Neuroscience software (e.g. FSL) here:  https://maastrichtu-ids.github.io/dsri-documentation/docs/neuroscience

And some example `Dockerfile` to build a workspace with FSL using Neurodocker (for CPU or GPU) here: https://github.com/MaastrichtU-IDS/jupyterlab
