### ISSUE TITLE
Issue deploying Trinityrnaseq

### ISSUE THREAD

**Issue by kamoors** [MaastrichtU-IDS/dsri-documentation#25]
### 2 Terminal within DSRI disconnects and all running function is stopped

 #1 
login to openshift as in documentation

oc get pods
oc rsh trinityrnaseq5-2-qzcxm

cd /usr/local/src/work2/aerius-sample-sequencing/CD4K4ANXX

Trinity --seqType fq --max_memory 100G --CPU 64 --samples_file samples.txt --output /usr/local/src/work2/Trinity_output_zip_090221

*Then the function starts like it should but at some points just exits without warnings or errors to my Windows folder*

#2 
Same application / same Trinity function. I first tried to do my analysis through DSRI in the container's terminal. Everything was running fine but my analysis never finishes. At some point a red label ''disconnected'' appears and the terminal stops and the analysis never continues.

Is there any way to continue a function within a container ''in the background'' / without me being connected to DSRI? Because it appears that the cisco VPN disconnects/reconnects and this causes some problems with DSRI..

Thank you for the help!

**Comment by kamoors** [comment]
Also, I forgot to mention but I cannot access my persistent storage within the container.

It was supposed to be under usr/local/src/work   

But that folder is empty. To access my files I added dynamic storage (that links with my persistent storage [which I access through File Browser])

**Comment by vemonet** [comment]
Hi @kamoors !

Those 2 issues are due to the process running attach to your terminal

You should be able to easily run it using the "Bash way": add `nohup` at the beginning and `&` at the end
It will run in the back and all output that should have gone to your terminal will go to a file `nohup.out` in the repo

```bash
nohup Trinity --seqType fq --max_memory 100G --CPU 64 --samples_file samples.txt --output /usr/local/src/work2/Trinity_output_zip_090221 &
```

To check if it is still running:

```bash
ps aux | grep Trinity
```

Be careful make sure the terminal uses bash and not shell ("sh")

To use bash just type bash in the terminal:

```bash
bash
```

> Then the function starts like it should but at some points just exits without warnings or errors to my Windows folder

Is it happening after a long time of connection? (e.g. after 1h of running the process?)

**Comment by kamoors** [comment]
*Is it happening after a long time of connection? (e.g. after 1h of running the process?)*

It happens very quickly after I start running the Trinity function. Otherwise it doesn't do that.

---------

I will try your solution! Thank you very much!

**Comment by kamoors** [comment]
![image](https://user-images.githubusercontent.com/35234605/107484875-51ab4a00-6b83-11eb-9745-1e5a13a300db.png)

Am I doing this right? I'm not really sure what should be happening... And if I type
ps aux | grep Trinity

what indicates whether it's running or not?

Thank you!

**Comment by vemonet** [comment]
In the image you are still running with Shell, (you should see the current path at the start of the commandline if bash is properly enabled)

Note: it has been fixed
