### ISSUE TITLE
Potentially confusing comment about `oc` command line interface

### ISSUE THREAD

**Issue by DennisSoemers** [MaastrichtU-IDS/dsri-documentation#42]
On [the "Access the DSRI" page](https://dsri.maastrichtuniversity.nl/docs/access-dsri), there is a brief note about halfway down about how it is recommended to install the `oc` command line interface. See screenshot:

![afbeelding](https://user-images.githubusercontent.com/5389687/177034791-b126c8b2-101f-4849-99ed-27fd2a491d22.png)

However, at this point there is no link yet to any instructions for how to do so, which [only shows up two pages later](https://dsri.maastrichtuniversity.nl/docs/openshift-install/). 

This can potentially be confusing. At least it was for me, in the sense that, when I saw that comment, I started googling around for where to download and install this client. That led me to redhat.com, where I'd have to register an account, and all sorts of annoying stuff, only to discover much later that the proper way to download it is to follow the instructions from 2 pages later.

**Comment by chriskuipers** [comment]
Good catch! I've linked the client instructions to the info box on the front page in 34f6caa.
