### ISSUE TITLE
Windows installation documentation does not work

### ISSUE THREAD

**Issue by vemonet** [MaastrichtU-IDS/dsri-documentation#9]
Windows documentation to install `oc` is deprecated: https://maastrichtu-ids.github.io/dsri-documentation/docs/openshift-install#on-windows
 
The URL returns 404 in

> Follow the [official documentation on Windows](https://docs.okd.io/latest/cli_reference/get_started_cli.html#cli-windows) to install the oc client.

It is not clear wherever the user should download the source code or the clean optimized ZIP for Windows

**Comment by vemonet** [comment]
![Screenshot from 2020-06-26 16-18-58](https://user-images.githubusercontent.com/3778439/85867271-ed40a380-b7c8-11ea-853d-4bc2739fdd3c.png)

The content of the `openshift-origin-client-tools-v3.11.0-0cbc58b-windows.zip` is clear and simple and has everything it needs for the user

We might even just provide the link to the GitHub download ZIP: so that they just click and does not need to go through the huge text written for the 3.11 release

**Comment by Binosha** [comment]
Added below download link and did some changes.
https://github.com/openshift/origin/releases/download/v3.7.2/openshift-origin-client-tools-v3.7.2-282e43f-windows.zip
